### ISSUE TITLE
[Suggestion] Add <world> parameter to openinv and opender

### ISSUE THREAD

**Issue by Jadiction** [lishid/OpenInv#122]
It'd be awesome if we could specify the world of the player's inventory we want to view. This could likely be done by hooking into Multiverse-Inventories.
It'd also be very helpful if we can known which world we're viewing the inventory from. Perhaps display the world name in chat after /openinv & /openender.

**Comment by Jikoo** [comment]
If you want to use an inventory modifying plugin (custom ender chests, per-gamemode inventories, etc.) it's on that plugin to offer editors for its inventories. If I add a hook for Multiverse-Inventories, why would I not then add a hook for each of the many dozen other plugins that offer similar functionality? I've personally used 4 alternatives over the years, and I'm aware of several more I never touched.

Barring the plugins themselves offering editors, this would be much better suited as an addon that hooks OpenInv and whatever other plugin, overriding `/oi` and `/oe`. Unfortunately, due to the scope, it is not a plugin I am willing to make - I've made the mistake of offering open-ended external plugin support before.

**Comment by Jadiction** [comment]
That's all fair. The only alternatives to Multiverse-Inventories that I've seen are PerWorldInventories and MultiInv; both of which are outdated. I'd say most (by a lot) server use Multiverse as their world management if they do use a world manager, so MV-Inv would be the choice if they wanted that functionality. The developer of Multiverse is busy and only provides fixes that are necessary as of right now, so that's why I was hoping for this plugin to hook rather than vice-versa. I understand your decline, though.
