### ISSUE TITLE
Loot generation also blocked by AnyContainer

### ISSUE THREAD

**Issue by Wolfst0rm** [lishid/OpenInv#142]
**OpenInv Version**: 4.1.2
**Spigot Version**: git-Spigot-ad703da-e2403a3 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Issue**: Incorrect Behaviour

**What Happens?** OP will go to a Bastion and proceed to attempt to open a chest and recieve the following issue:

![image](https://user-images.githubusercontent.com/18635695/86119799-6d218300-bad3-11ea-92c6-80070784a37d.png)

OP proceeds to disable silentcontainer, issue still occurs. However a normal user without the permission for OpenInv.SilentContainer, can open the chest and retrieve the items just fine.

**What Should Happen?** Chest will have generated and OPs should be able to retrieve the items from the chest.

**Comment by Jikoo** [comment]
Pretty sure I know where this is, though I thought I had tested it pretty thoroughly. Should affect all un-generated loot, not just bastions.

**Comment by Jikoo** [comment]
This specifically also is only a problem for double chests.

**Comment by CowedOffACliff** [comment]
I would just like to chime in and confirm that this is an issue with the latest 1.16 release of the plugin. As an OP on my server I cannot naturally open double loot chests due to this bug. Any regular single loot chest will work correctly with silent inventory disabled as expected. The issue does not affect regular users that lack the permission.

**Comment by Jikoo** [comment]
[4.1.3](https://github.com/lishid/OpenInv/releases/tag/4.1.3)
