### ISSUE TITLE
Items not removing from players inventories

### ISSUE THREAD

**Issue by Cyclopeanserver** [lishid/OpenInv#167]
When removing items from an offline player's inventory, the moderator gets the items but the item is not removed from the player's inventory when they log in. Running latest Paper version for 1.16.4. I understand the plugin may not be up to date with 1.16.4, but thought you should know.

**Comment by Jikoo** [comment]
OpenInv version? Server version? Latest is not a valid version. Cannot reproduce on Paper 279 with OpenInv 4.1.5.

OpenInv has been updated to 1.16.4 for a while now.

**Comment by Jikoo** [comment]
Going to close this due to inability to reproduce and lack of response.

This is probably a conflict with another plugin. If you can find a reliable reproduction technique, remove half your plugins at a time until you find the conflict. I'm willing to help you trace through the code once you can pinpoint a plugin (assuming the plugin is open source) but you'll need to figure out the incompatible plugin yourself.

**Comment by 46620** [comment]
A possible plugin that might be causing this is SaberFactions, was testing and found this plugin broke moving items. Currently trying to figure out how to get them to work together.

**Comment by Jikoo** [comment]
https://github.com/SaberLLC/Saber-Factions/blob/17e44373d4bd2d223b48ea2b2388c8c15b33976d/src/main/java/com/massivecraft/factions/listeners/FactionsPlayerListener.java#L851-L856

SaberFactions always cancels all click events in inventories with names ending in "'s Inventory" so you can circumvent the conflict by changing the inventory name pattern in your OpenInv lang settings.
