### ISSUE TITLE
Not allowing to edit inventory

### ISSUE THREAD

**Issue by Silent-Program** [lishid/OpenInv#169]
I can not edit peoples inventorys. I am opped, and i have given myself the permission. However i cannot interact with inventorys. I can however interact with enderchests.

**Comment by Silent-Program** [comment]
I just read a previous thing with same issue. Luckperms does not allow you to use capitol letters in permissions.

**Comment by Silent-Program** [comment]
![image](https://user-images.githubusercontent.com/72319773/100043241-d6c36600-2dc1-11eb-9d64-70adabe31e8c.png)
yet i cant move anthing around

**Comment by Jikoo** [comment]
Great, if you read the previous issue then you already know what I'm going to say. You need to use verbose mode with LP to diagnose your issues. Unlike the other person, you've actually told me you're using LP, though neither of you bothered to tell me what OI version you're running nor the actual server implementation. That means I can tell you that LP is case-insensitive, so you don't need to worry about capitalization.

Do me a solid and don't mess with the wiki unless you're going to write useful pages, thanks.

Now I'm going to write up a boilerplate paragraph so I can paste it into future similar issues.

OpenInv works fine without other plugins installed, which means its permissions for editing inventories are working as intended with the presets provided for Bukkit's inbuilt SuperPerms system. Unfortunately, due to the number of variables involved, I cannot diagnose your permissions issue. Your best bet is to use a system such as LuckPerm's verbose mode that tells you real-time what permissions are being checked for whom and how they evaluate. If you can provide enough information to indicate an actual OpenInv issue I will be happy to look into it, but until such a time the sheer number of things that could be wrong force me to assume that you have made a mistake in your permissions configuration.
