### ISSUE TITLE
OpenInv keeps containers open

### ISSUE THREAD

**Issue by leasoncre** [lishid/OpenInv#176]
Paper 1.16.5-457
if ii open a container when not in vanish, the container stays visually open for any client that has been in the area when it was opened by an admin (this includes shulker boxes that increase their hitbox, and stay open)
only fix is to relog/re-place container

tested on shulker box, chest, and large_chest. 
when openinv is unloaded on test server, new chests/unopened-chests don't stay open.

**Comment by Jikoo** [comment]
Sounds like an incompatibility with your vanish plugin. Please reproduce using only OpenInv.

**Comment by Jikoo** [comment]
I'm gonna write up a boilerplate explanation as to why that's probably happening here because this is the second of these issues in 2 days.

The reason you're likely seeing containers "freeze open" is that you are running a vanish plugin that attempts to implement its own SilentContainer functionality. Unfortunately, most vanish plugins cancel packets and cause Minecraft's internals to become confused. Because the internals are in the wrong state or the packets were intercepted, the close packets do not get sent to the client.
OpenInv, instead of messing around with packets and producing invalid server states, forces the container to treat the user as a spectator. This has the same effect - trapped chests don't trigger, sounds and animations don't play - while preventing the server from getting confused about what packets should be sent when.

If your vanish plugin has the capability, have it disable OpenInv's SilentContainer functionality while enabled.

**Comment by leasoncre** [comment]
i use SuperVanish, which also states it uses the spectator mode to open chests....
BUT at no point was i in vanish, so it shouldn't be related?

**Comment by Jikoo** [comment]
> Please reproduce using only OpenInv.

**Comment by leasoncre** [comment]
for some reason i had `openinv.silent FALSE` set on my player in LuckPerms, WITH it enabled.... must have done derped ages ago and never looked into it.
+Removing that node and turning it off fixed the issue
thank you
-fixed/resolved

**Comment by leasoncre** [comment]
ONE thing to note with this is that after changing the silentchest setting to off... .containers already stuck open do not fix themselves until relogging (not even by re-opening them, which i would have expected to work)
