### ISSUE TITLE
Offline Player on horse

### ISSUE THREAD

**Issue by rumickon** [lishid/OpenInv#22]
When player logout on horse and somebody changing him inventory, the horse will be disappear.

**Comment by Jikoo** [comment]
Had a look into this, my suspicion is that the chunk the player is in is unloaded. Haven't tested yet, but we may be able to fix it by keeping the chunks players are in loaded rather than rewriting the entire save process to use NMS.

When a player logs in, their mount is read out of the NBT tag. If it exists, it's spawned and the player is set riding it. When we go to save, the entity does not exist any more.
