### ISSUE TITLE
Port to Forge

### ISSUE THREAD

**Issue by vpontin** [lishid/OpenInv#50]
Hi!

I know this is a silly question, but are there any plans to port this very useful plugin to Forge?

I think only permissions should be different: just op/non-op.

Thanks in advance!

**Comment by Jikoo** [comment]
I personally have no plans to port OpenInv to Forge. It would be much easier to just make a separate Forge mod that works in the same manner. OpenInv is relatively small, making it platform-agnostic would practically take more code than the plugin itself.

Regarding permissions, Bukkit's system causes all OpenInv permissions to default to op, so that's already a feature.
