### ISSUE TITLE
PlayerInteractEvent 1.13.2

### ISSUE THREAD

**Issue by seema84** [lishid/OpenInv#94]
Spigot 1.13.2 (last build from 28.12.2018)

https://pastebin.com/Kpk2C6Fr

**Comment by Sermuns** [comment]
Also getting precisely this error spammed in console.
Running Spigot-518206a-a5b9c7b

**Comment by FabioZumbi12** [comment]
Same error here!

**Comment by NobleStrike** [comment]
Same here. Its blowing my console with that error like crazy.

**Comment by RoboMWM** [comment]
5 comments from 5 people and none saying under what conditions it occurs...

**Comment by seema84** [comment]
you can see it in the stacktrace (if a player open a shulkerbox)
more is not needed for it

**Comment by FabioZumbi12** [comment]
Because the stacktrace is engouht: `Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.VoxelShape.a()Lnet/minecraft/server/v1_13_R2/AxisAlignedBB;`

Something changed (and removed) from latest builds of Spigot/Paper

**Comment by RoboMWM** [comment]
idk how the stacktrace is enough, yes a method was removed but still doesn't dictate what circumstances cause that to be called.

Thanks seema84.

**Comment by RoboMWM** [comment]
Oh, I think I know why - md_5 changed mappings and didn't bother to bump the NMS version to "prevent breaking plugins"

Except he broke many significant NMS plugins like this, holographicdisplays, and some others people complained about afaik...

**Comment by Jikoo** [comment]
Hey guys, sorry I haven't gotten to this yet (or replied) - Robo is correct, there was a NMS mappings update without a NMS revision change.

My PC is currently broken, GPU is fried. I expect to be able to make some sort of inroads on the various issues that have cropped up in the past month or so by this weekend, but I'm out of commission for at least a couple more days.

**Comment by i0xHeX** [comment]
`VoxelShape.a()`
now
`VoxelShape.getBoundingBox()`

**Comment by i0xHeX** [comment]
Quick fix guys!
[OpenInv-3.3.6-p1.zip](https://github.com/lishid/OpenInv/files/2753278/OpenInv-3.3.6-p1.zip)

**Comment by RoboMWM** [comment]
@i0xHeX mind linking source, or better yet making a PR?

**Comment by crashdemons** [comment]
In case there's no response, here's a diff between decompiles of 3.3.6 and 3.3.6-p1 which might highlight the edits done.  I might have missed something because I only one class appeared to have newer timestamp.

https://github.com/crashdemons/OpenInv/commit/6c8321a4f1ed60a790139b507c1a21791a447e2e 
(don't pull this, it lacks comments and has some bad commit in history)

**Comment by i0xHeX** [comment]
> In case there's no response, here's a diff between decompiles of 3.3.6 and 3.3.6-p1 which might highlight the edits done. I might have missed something because I only saw one class that appeared to have a newer timestamp.
> 
> [crashdemons@6c8321a](https://github.com/crashdemons/OpenInv/commit/6c8321a4f1ed60a790139b507c1a21791a447e2e)
> (don't pull this, it lacks comments and has some bad commits in history)
> 
> EDIT: there shouldn't be any licensing issues with using this as an indicator because it's derivative under GPL

The only change needed to source is
`VoxelShapes.b().a()`
to
`VoxelShapes.b().getBoundingBox()`

All other changes are defect after decompilation / compilation.
I'm have no time to clone / pull request / build from sources. I made fast patch for my server and posted for anyone wants quick fix.

**Comment by crashdemons** [comment]
that's kind of what I figured and that the renaming of some other things was immaterial, but I wanted to be sure to document everything.:

I wonder if that change will break older 1.13.1 servers (and even older 1.13.2 builds, but they could rebuild?) relying on the same "internal" since it would still be `a` on un-updated ones.

Would a new internal be added for that case separately, or does it need to be checked with method reflection because of the version being the same?  (Or should users just update the server?)

**Comment by i0xHeX** [comment]
> I wonder though if that change will break older 1.13.1 servers (and even older 1.13.2 builds, but they could rebuild?) relying on the same "internal" since it would still be `a` on un-updated ones.
> 
> Would a new internal be added for that case separately, or does it need to be checked with method reflection because of the version being the same? (Or should users just update the server instead?)

I think everybody should use latest 1.13.x build if on 1.13 major version. Just drop support.

**Comment by Jikoo** [comment]
>I wonder though if that change will break older 1.13.1 servers (and even older 1.13.2 builds, but they could rebuild?) relying on the same "internal" since it would still be a on un-updated ones.
>
>Would a new internal be added for that case separately, or does it need to be checked with method reflection because of the version being the same? (Or should users just update the server instead?)

It would break older versions of 1.13. Because md_5 elected not to bump nms version, without going back and rewriting lishid's loader and any relevant internal classes, it's not possible to make a separate version.

In happier news, I finally finished yet another stage of repair, so I've managed to retrieve my usual ~~horrible mess~~ workspace setup.

**Comment by Jikoo** [comment]
Okay, this should work: [OpenInv.zip](https://github.com/lishid/OpenInv/files/2762142/OpenInv.zip) I cannot test, because apparently Minecraft does not support the sweet sweet Intel integrated graphics driver I'm currently rocking. Feedback appreciated before I just blindly push out a release.

**Comment by takatalvi** [comment]
@Jikoo this build seems to be working just fine! Thanks so much!

**Comment by Jikoo** [comment]
[3.3.7](https://github.com/lishid/OpenInv/releases/tag/3.3.7)
